### ISSUE TITLE
InstantShare client should support movie file uploads (from disk).

### ISSUE THREAD

**Issue by pavben** [pavben/InstantShare#9]
The server was designed with this in mind, so it's possible to stream large files as they're being uploaded.

## Desired behavior

When clicking "Instant Share", if the clipboard contains a file, follow these steps:

1. Send the initial request to the InstantShare server, providing the file extension and getting back a link where the file can be accessed once the upload begins.
2. Stream the file content to upload it.

**Comment by shurcooL** [comment]
Proposed API change to support uploading files, while preserving their original filename:

```
/getfilename?ext=png
/getfilename?filename=an-existing-file.jpg
```

Which uploads to:

```
http://host/{{.Random}}.png
http://host/{{.Random}}/an-existing-file.jpg
```

**Comment by shurcooL** [comment]
I've changed this issue to be specific to movie file uploads, since that's what PR #13 adds support for now.

More file extensions can be supported later, and deserves a separate issue and PR.
